### ISSUE TITLE
Rationale for measurement of Fortran 'write' statement.

### ISSUE THREAD

**Issue by bgin** [jacobwilliams/minnorm_test#2]
Dear Jacob

Can you explain what is the rationale or reason for measuring the performance of the 'write' statement?
Secondly, what is the reason for measuring the zero filling (a memset call) and allocate (a memcpy call(s))
statements, which will directly skew the expected results by addition of large amount of unpredictable 
machine code activity spanning across at least two executables.
Thirdly, I completely ignore the issue of single measurement, which is totally unpredictable from the statistical point of view.
The link to aforementioned case.
https://github.com/jacobwilliams/minnorm_test/blob/master/src/minnorm_module.f90#L118

**Comment by jacobwilliams** [comment]
the reason is that I made this example very quickly. :) 

the write statement was just for debuging. it can be removed. but it takes minutes to run this, so the write statement isn't doing much.

The intent is to time how long it takes to get a solution, starting from the sparse matrix, so all that stuff needs to be there since you have to do that to get the solution. Now that I look at it, I should move the `a_dense` stuff into the timing too.

yep, it's just a single example for testing.

**Comment by bgin** [comment]
> the reason is that I made this example very quickly. :)
> 
> the write statement was just for debuging. it can be removed. but it takes minutes to run this, so the write statement isn't doing much.
> 
> The intent is to time how long it takes to get a solution, starting from the sparse matrix, so all that stuff needs to be there since you have to do that to get the solution. Now that I look at it, I should move the `a_dense` stuff into the timing too.
> 
> yep, it's just a single example for testing.

Dear Jacob

Thank you for the answer.

Here is an example (albeit at advanced level) of performance measurement test.
A performance single standalone WRF module was measured by means of reading CPU performance counters (essentially a few lines of inline assembly routines called by the corresponding Fortran wrappers).
https://github.com/bgin/Radar_ElectroOptical_Simulation/blob/master/Atmosphere_model/GMS_wsm6_driver.f90#L380

Best regards

Bernard
